app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['web', 'auth']], function () {
    Route::get('roles', ['as' => 'roles.index', 'uses' => 'Admin\RolesController@index']);
    Route::get('roles/new', ['as' => 'roles.create', 'uses' => 'Admin\RolesController@create']);
    Route::post('roles/store', ['as' => 'roles.store', 'uses' => 'Admin\RolesController@store']);
    Route::get('roles/edit/{id}', ['as' => 'roles.edit', 'uses' => 'Admin\RolesController@edit']);
    Route::put('roles/update/{id}', ['as' => 'roles.update', 'uses' => 'Admin\RolesController@update']);
    Route::get('roles/destroy/{id}', ['as' => 'roles.destroy', 'uses' => 'Admin\RolesController@destroy']);
    Route::get('roles/permissions/{id}', ['as' => 'roles.permissions', 'uses' => 'Admin\RolesController@permissions']);
    Route::post('roles/permissions/{id}/store', ['as' => 'roles.permissions.store', 'uses' => 'Admin\RolesController@storePermission']);
    Route::get('roles/permissions/{id}/revoke/{permission_id}', ['as' => 'roles.permissions.revoke', 'uses' => 'Admin\RolesController@revokePermission']);

    Route::get('permissions', ['as' => 'permissions.index', 'uses' => 'Admin\PermissionsController@index']);
    Route::get('permissions/new', ['as' => 'permissions.create', 'uses' => 'Admin\PermissionsController@create']);
    Route::post('permissions/store', ['as' => 'permissions.store', 'uses' => 'Admin\PermissionsController@store']);
    Route::get('permissions/edit/{id}', ['as' => 'permissions.edit', 'uses' => 'Admin\PermissionsController@edit']);
    Route::put('permissions/update/{id}', ['as' => 'permissions.update', 'uses' => 'Admin\PermissionsController@update']);
    Route::get('permissions/destroy/{id}', ['as' => 'permissions.destroy', 'uses' => 'Admin\PermissionsController@destroy']);

    Route::get('users', ['as' => 'users.index', 'uses' => 'Admin\UsersController@index']);
    Route::get('users/new', ['as' => 'users.create', 'uses' => 'Admin\UsersController@create']);
    Route::post('users/store', ['as' => 'users.store', 'uses' => 'Admin\UsersController@store']);
    Route::get('users/edit/{id}', ['as' => 'users.edit', 'uses' => 'Admin\UsersController@edit']);
    Route::put('users/update/{id}', ['as' => 'users.update', 'uses' => 'Admin\UsersController@update']);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'Admin\UsersController@destroy']);
    Route::get('users/roles/{id}', ['as' => 'users.roles', 'uses' => 'Admin\UsersController@roles']);
    Route::post('users/roles/{id}/store', ['as' => 'users.roles.store', 'uses' => 'Admin\UsersController@storeRole']);
    Route::get('users/roles/{id}/revoke/{role_id}', ['as' => 'users.roles.revoke', 'uses' => 'Admin\UsersController@revokeRole']);

    Route::get('categories', ['as' => 'categories.index', 'uses' => 'Admin\CategoriesController@index']);
    Route::get('categories/new', ['as' => 'categories.create', 'uses' => 'Admin\CategoriesController@create']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\CategoriesController@store']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\CategoriesController@edit']);
    Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\CategoriesController@update']);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\CategoriesController@destroy']);

    Route::get('books', ['as' => 'books.index', 'uses' => 'Admin\BooksController@index']);
    Route::get('books/new', ['as' => 'books.create', 'uses' => 'Admin\BooksController@create']);
    Route::post('books/store', ['as' => 'books.store', 'uses' => 'Admin\BooksController@store']);
    Route::get('books/edit/{id}', ['as' => 'books.edit', 'uses' => 'Admin\BooksController@edit']);
    Route::put('books/update/{id}', ['as' => 'books.update', 'uses' => 'Admin\BooksController@update']);
    Route::get('books/destroy/{id}', ['as' => 'books.destroy', 'uses' => 'Admin\BooksController@destroy']);
    Route::get('books/cover/{id}', ['as'=>'books.cover', 'uses'=>'Admin\BooksController@cover']);
    Route::post('books/cover/{id}', ['as'=>'books.cover.store', 'uses'=>'Admin\BooksController@coverStore']);
    Route::get('books/export/{id}', ['as'=>'books.export', 'uses'=>'Admin\BooksController@export']);

    Route::group(['prefix'=>'books', 'as'=>'books.'], function () {
        Route::get('{id}/chapters', ['as'=>'chapters.index', 'uses'=>'Admin\ChaptersController@index']);
        Route::get('{id}/chapters/create', ['as'=>'chapters.create', 'uses'=>'Admin\ChaptersController@create']);
        Route::post('{id}/chapters/store', ['as'=>'chapters.store', 'uses'=>'Admin\ChaptersController@store']);
        Route::get('{id}/chapters/edit/{chapter_id}', ['as'=>'chapters.edit', 'uses'=>'Admin\ChaptersController@edit']);
        Route::put('{id}/chapters/update/{chapter_id}', ['as'=>'chapters.update', 'uses'=>'Admin\ChaptersController@update']);
        Route::get('{id}/chapters/destroy/{chapter_id}', ['as'=>'chapters.destroy', 'uses'=>'Admin\ChaptersController@destroy']);
    });
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
});

app/Models/Role.php
<?php

namespace CodePub\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name', 'description'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function addPermission(Permission $permission)
    {
        return $this->permissions()->save($permission);
    }

    public function revokePermission(Permission $permission)
    {
        return $this->permissions()->detach($permission);
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace CodePub\Http\Controllers\Admin;

use CodePub\Models\Permission;
use CodePub\Models\Role;
use Illuminate\Http\Request;

use CodePub\Http\Requests;
use CodePub\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;

class RolesController extends Controller
{

    public function __construct()
    {
        if( !App::runningInConsole() ) {
            $this->authorize('role_admin');
        }
    }

    public function index()
    {
        $roles = Role::all();

        return view('admin.roles.index', compact('roles'));
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(Request $request)
    {
        Role::create($request->all());
        return redirect()->route('admin.roles.index');
    }

    public function edit($id)
    {
        $role = Role::find($id);
        return view('admin.roles.edit', compact('role'));
    }

    public function update(Request $request, $id)
    {
        Role::find($id)->update($request->all());
        return redirect()->route('admin.roles.index');
    }

    public function destroy($id)
    {
        Role::find($id)->delete();
        return redirect()->route('admin.roles.index');
    }

    public function permissions($id)
    {
        $role = Role::find($id);
        $permissions = Permission::all();

        return view('admin.roles.permissions', compact('role', 'permissions'));
    }

    public function storePermission(Request $request, $id)
    {
        $role = Role::find($id);

        $permission = Permission::findOrFail($request->all()['permission_id']);

        $role->addPermission($permission);

        return redirect()->back();
    }

    public function revokePermission($id, $permission_id)
    {
        $role = Role::find($id);
        $permission = Permission::find($permission_id);

//        $role->permissions()->detach($permission);
        $role->revokePermission($permission);

        return redirect()->back();

    }

}

resources/views/admin/roles/_form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Create new role</h2>

        {!! Form::open(['route' => 'admin.roles.store']) !!}

        @include('admin.roles._form')

        {!! Form::submit('Add role', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
    </div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Editing role: {{$role->name}}</h2>

        {!! Form::model($role, ['route' => ['admin.roles.update', $role->id], 'method' => 'put']) !!}

        @include('admin.roles._form')

        {!! Form::submit('Save role', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
    </div>

@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Roles</h2>

        <a href="{{route('admin.roles.create')}}" class="btn btn-link">Create</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
            </thead>
            @foreach($roles as $role)
                <tr>
                    <td>{{$role->name}}</td>
                    <td>{{$role->description}}</td>
                    <td>

                        <a href="{{route('admin.roles.edit', ['id' => $role->id])}}" class="btn btn-default">Edit</a>
                        <a href="{{route('admin.roles.permissions', ['id' => $role->id])}}" class="btn btn-default">Permissions</a>
                        <a href="{{route('admin.roles.destroy', ['id' => $role->id])}}" class="btn btn-danger">Destroy</a>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

resources/views/admin/roles/permissions.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Permissions of {{$role->name}}</h2>
        <br>
        <h3>Add new permission</h3>

        {!! Form::open(['route' => ['admin.roles.permissions.store', $role->id]]) !!}

        <select name="permission_id" class="form-control">
            @foreach($permissions as $permission)
                <option value="{{$permission->id}}">{{$permission->name}}</option>
            @endforeach
        </select>
        <br>

        {!! Form::submit('Add permission', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}

        <br>
        <table class="table table-bordered">
            <thead>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
            </thead>
            @foreach($role->permissions as $permission)
                <tr>
                    <td>{{$permission->name}}</td>
                    <td>{{$permission->description}}</td>
                    <td>
                        <a href="{{route('admin.roles.permissions.revoke', ['id' => $role->id, 'permission_id' => $permission->id])}}" class="btn btn-danger">Revoke</a>
                    </td>
                </tr>
            @endforeach
        </table>

        <a href="{{route('admin.roles.index')}}">Back</a>
    </div>
@endsection