app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['web', 'auth']], function () {
    Route::get('roles', ['as' => 'roles.index', 'uses' => 'Admin\RolesController@index']);
    Route::get('roles/new', ['as' => 'roles.create', 'uses' => 'Admin\RolesController@create']);
    Route::post('roles/store', ['as' => 'roles.store', 'uses' => 'Admin\RolesController@store']);
    Route::get('roles/edit/{id}', ['as' => 'roles.edit', 'uses' => 'Admin\RolesController@edit']);
    Route::put('roles/update/{id}', ['as' => 'roles.update', 'uses' => 'Admin\RolesController@update']);
    Route::get('roles/destroy/{id}', ['as' => 'roles.destroy', 'uses' => 'Admin\RolesController@destroy']);
    Route::get('roles/permissions/{id}', ['as' => 'roles.permissions', 'uses' => 'Admin\RolesController@permissions']);
    Route::post('roles/permissions/{id}/store', ['as' => 'roles.permissions.store', 'uses' => 'Admin\RolesController@storePermission']);
    Route::get('roles/permissions/{id}/revoke/{permission_id}', ['as' => 'roles.permissions.revoke', 'uses' => 'Admin\RolesController@revokePermission']);

    Route::get('permissions', ['as' => 'permissions.index', 'uses' => 'Admin\PermissionsController@index']);
    Route::get('permissions/new', ['as' => 'permissions.create', 'uses' => 'Admin\PermissionsController@create']);
    Route::post('permissions/store', ['as' => 'permissions.store', 'uses' => 'Admin\PermissionsController@store']);
    Route::get('permissions/edit/{id}', ['as' => 'permissions.edit', 'uses' => 'Admin\PermissionsController@edit']);
    Route::put('permissions/update/{id}', ['as' => 'permissions.update', 'uses' => 'Admin\PermissionsController@update']);
    Route::get('permissions/destroy/{id}', ['as' => 'permissions.destroy', 'uses' => 'Admin\PermissionsController@destroy']);

    Route::get('users', ['as' => 'users.index', 'uses' => 'Admin\UsersController@index']);
    Route::get('users/new', ['as' => 'users.create', 'uses' => 'Admin\UsersController@create']);
    Route::post('users/store', ['as' => 'users.store', 'uses' => 'Admin\UsersController@store']);
    Route::get('users/edit/{id}', ['as' => 'users.edit', 'uses' => 'Admin\UsersController@edit']);
    Route::put('users/update/{id}', ['as' => 'users.update', 'uses' => 'Admin\UsersController@update']);
    Route::get('users/destroy/{id}', ['as' => 'users.destroy', 'uses' => 'Admin\UsersController@destroy']);
    Route::get('users/roles/{id}', ['as' => 'users.roles', 'uses' => 'Admin\UsersController@roles']);
    Route::post('users/roles/{id}/store', ['as' => 'users.roles.store', 'uses' => 'Admin\UsersController@storeRole']);
    Route::get('users/roles/{id}/revoke/{role_id}', ['as' => 'users.roles.revoke', 'uses' => 'Admin\UsersController@revokeRole']);

    Route::get('categories', ['as' => 'categories.index', 'uses' => 'Admin\CategoriesController@index']);
    Route::get('categories/new', ['as' => 'categories.create', 'uses' => 'Admin\CategoriesController@create']);
    Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'Admin\CategoriesController@store']);
    Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'Admin\CategoriesController@edit']);
    Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'Admin\CategoriesController@update']);
    Route::get('categories/destroy/{id}', ['as' => 'categories.destroy', 'uses' => 'Admin\CategoriesController@destroy']);

    Route::get('books', ['as' => 'books.index', 'uses' => 'Admin\BooksController@index']);
    Route::get('books/new', ['as' => 'books.create', 'uses' => 'Admin\BooksController@create']);
    Route::post('books/store', ['as' => 'books.store', 'uses' => 'Admin\BooksController@store']);
    Route::get('books/edit/{id}', ['as' => 'books.edit', 'uses' => 'Admin\BooksController@edit']);
    Route::put('books/update/{id}', ['as' => 'books.update', 'uses' => 'Admin\BooksController@update']);
    Route::get('books/destroy/{id}', ['as' => 'books.destroy', 'uses' => 'Admin\BooksController@destroy']);
    Route::get('books/cover/{id}', ['as'=>'books.cover', 'uses'=>'Admin\BooksController@cover']);
    Route::post('books/cover/{id}', ['as'=>'books.cover.store', 'uses'=>'Admin\BooksController@coverStore']);
    Route::get('books/export/{id}', ['as'=>'books.export', 'uses'=>'Admin\BooksController@export']);

    Route::group(['prefix'=>'books', 'as'=>'books.'], function () {
        Route::get('{id}/chapters', ['as'=>'chapters.index', 'uses'=>'Admin\ChaptersController@index']);
        Route::get('{id}/chapters/create', ['as'=>'chapters.create', 'uses'=>'Admin\ChaptersController@create']);
        Route::post('{id}/chapters/store', ['as'=>'chapters.store', 'uses'=>'Admin\ChaptersController@store']);
        Route::get('{id}/chapters/edit/{chapter_id}', ['as'=>'chapters.edit', 'uses'=>'Admin\ChaptersController@edit']);
        Route::put('{id}/chapters/update/{chapter_id}', ['as'=>'chapters.update', 'uses'=>'Admin\ChaptersController@update']);
        Route::get('{id}/chapters/destroy/{chapter_id}', ['as'=>'chapters.destroy', 'uses'=>'Admin\ChaptersController@destroy']);
    });
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');
});

app/Models/Book.php
<?php

namespace CodePub\Models;

use CodePub\Models\BookInterface;
use Illuminate\Database\Eloquent\Model;

class Book extends Model implements BookInterface
{
    protected $fillable = [
        'user_id',
        'category_id',
        'title',
        'subtitle',
        'dedication',
        'description',
        'website',
        'percent_complete',
        'price',
        'published'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function chapters()
    {
        return $this->hasMany(Chapter::class);
    }
}

app/Http/Controllers/Admin/BooksController.php
<?php

namespace CodePub\Http\Controllers\Admin;

use CodePub\Events\GenerateBook;
use CodePub\Models\Book;
use CodePub\Models\Category;
use CodePub\Services\BookService;
use Illuminate\Http\Request;

use CodePub\Http\Requests;
use CodePub\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Event;

class BooksController extends Controller
{
    public function index()
    {
        if (auth()->user()->can('book_manage_all')) {
            $books = Book::all();
        } else {
            $books = Book::whereUserId(auth()->user()->id)->get();
        }

        return view('admin.books.index', compact('books'));
    }

    public function create()
    {
        $categories = Category::lists('name', 'id');
        return view('admin.books.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $input = $request->all();
        $input['user_id'] = auth()->user()->id;
        Book::create($input);
        return redirect()->route('admin.books.index');
    }

    public function edit($id)
    {
        $book = Book::find($id);

        if (Gate::denies('manage', $book)) {
            abort(403, 'You dont own this book');
        }

        $categories = Category::lists('name', 'id');
        return view('admin.books.edit', compact('book', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $book = Book::find($id);

        if (Gate::denies('manage', $book)) {
            abort(403, 'You dont own this book');
        }

        $book->update($request->all());
        return redirect()->route('admin.books.index');
    }

    public function destroy($id)
    {
        $book = Book::find($id);

        if (Gate::denies('manage', $book)) {
            abort(403, 'You dont own this book');
        }

        $book->delete();
        return redirect()->route('admin.books.index');
    }

    public function cover($id)
    {
        $book = Book::find($id);

        if (Gate::denies('manage', $book)) {
            abort(403, 'You dont own this book');
        }

        return view('admin.books.cover', compact('book'));
    }

    public function coverStore(Request $request, $id)
    {
        $book = Book::find($id);

        if (Gate::denies('manage', $book)) {
            abort(403, 'You dont own this book');
        }

        //fazer upload de livro é regra de negocio
        //controller sempre eh pequeno, ele é intermediario recebe a request executa o que tem q executar
        //e retorna uma response

        $bookService = app()->make(BookService::class);
        $bookService->storeCover($book, $request->file('file'));

        return redirect()->back();
    }

    public function export($id)
    {
        $book = Book::find($id);
        if(Gate::denies('manage', $book)) {
            abort(403,'You dont own this book');
        }

        Event::fire(new GenerateBook($book));

        return redirect()->route('admin.books.index');
    }

}

resources/views/admin/books/_form.blade.php
<div class="form-group">
    {!! Form::label('category_id', 'Category:') !!}
    {!! Form::select('category_id', $categories, null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('subtitle', 'Subtitle:') !!}
    {!! Form::text('subtitle', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('dedication', 'Dedication:') !!}
    {!! Form::textarea('dedication', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('website', 'Website:') !!}
    {!! Form::text('website', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('percent_complete', 'Percent Complete:') !!}
    {!! Form::text('percent_complete', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('price', 'Price:') !!}
    {!! Form::text('price', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('published', 'Published:') !!}
    {!! Form::checkbox('published') !!}
</div>

resources/views/admin/books/cover.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Cover of: {{$book->title}}</h2>

        @if (file_exists(public_path('/books/thumbs/' . $book->id . '.jpg')))
            <img src="/books/thumbs/{{$book->id}}.jpg">
        @endif

        {!! Form::open(['route' => ['admin.books.cover.store', $book->id], 'enctype' => 'multipart/form-data']) !!}

        <div class="form-group">
            {!! Form::label('file', 'Cover:') !!}
            {!! Form::file('file', null, ['class'=>'form-control']) !!}
        </div>

        {!! Form::submit('Upload', ['class'=>'btn btn-primary']) !!}

        {!! Form::close() !!}
        <br>
        <a href="{{route('admin.books.index')}}" class="btn btn-sm btn-default">Back</a>

    </div>
@endsection

resources/views/admin/books/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Create new book</h2>

        {!! Form::open(['route' => 'admin.books.store']) !!}

        @include('admin.books._form')

        {!! Form::submit('Add book', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
    </div>

@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Editing category: {{$book->title}}</h2>

        {!! Form::model($book, ['route' => ['admin.books.update', $book->id], 'method' => 'put']) !!}

        @include('admin.books._form')

        {!! Form::submit('Save book', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Books</h2>

        <a href="{{route('admin.books.create')}}" class="btn btn-link">Create</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <th>Title</th>
            <th>Author</th>
            <th>Action</th>
            </thead>
            @foreach($books as $book)
                <tr>
                    <td>{{$book->title}}</td>
                    <td>{{$book->author->name}}</td>
                    <td>

                        <a href="{{route('admin.books.edit', ['id' => $book->id])}}" class="btn btn-default">Edit</a>
                        <a href="{{route('admin.books.chapters.index',['id'=>$book->id])}}" class="btn btn-default">Chapters</a>
                        <a href="{{route('admin.books.destroy', ['id' => $book->id])}}" class="btn btn-danger">Destroy</a>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection